- name: Include ami preparation-specific variables
  include_vars:
    file: 'ami_preparation.yaml'

- name: Check server
  fail:
    msg: "This role does not support installation of MongoDB on other OS than CentOS 7"
  when: (ansible_distribution != "CentOS") or (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7")

- name: Check if necessary variables are defined
  fail:
    msg: "{{item}} variable not defined"
  when: item not in vars
  with_items: "{{mongodb_required_variables}}"

- name: Check MongoDB version support
  fail:
    msg: "Sorry, this role does not support installation of MongoDB {{mongodb_version}}"
    with_items: "{{mongodb_acceptable_versions}}"
  when: mongodb_version not in mongodb_acceptable_versions

- name: Disable selinux
  selinux:
    state: disabled

- name: Install pymongo
  pip:
    name: pymongo
    state: present

- name: Enable MongoDB repository for MongoDB {{mongodb_version}}
  template:
    src: yum_repository.j2
    dest: /etc/yum.repos.d/mongodb.repo
    mode: 0644

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: latest

- name: Apply MongoDB configuration
  template:
    src: mongodb.conf.j2
    dest: "{{mongodb_configuration_file}}"

- name: Create MongoDB logs directory
  file:
    path: "{{mongodb_log_directory}}"
    state: directory
    mode: 0755
    owner: "{{mongodb_user}}"
    group: "{{mongodb_group}}"

- name: Create MongoDB database directory
  file:
    path: "{{mongodb_db_directory}}"
    state: directory
    mode: 0755
    owner: "{{mongodb_user}}"
    group: "{{mongodb_group}}"

- name: Start and enable MongoDB service during system boot
  service:
    state: started
    name: mongod
    enabled: true

- name: Create systemd unit for disabling transparent hugepages
  template:
    src: disable_transparent_hugepages.service.j2
    dest: /etc/systemd/system/disable_transparent_hugepages.service
    mode: 0750
    owner: root
    group: root

- name: Enable and start disable_transparent_hugepages service
  service:
    name: disable_transparent_hugepages
    state: started
    enabled: true

- name: Adjust OS limits to mongod requirements
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.d/10-mongod.conf
    mode: 0644
    owner: root
    group: root

- name: Create core administrative user
  ignore_errors: true
  mongodb_user:
    login_port: "{{mongodb_port}}"
    database: admin
    name: "{{mongodb_admin_username}}"
    password: "{{mongodb_admin_password}}"
    roles: root
    state: present

- name: Create monitoring user
  mongodb_user:
    login_user: "{{mongodb_admin_username}}"
    login_password: "{{mongodb_admin_password}}"
    login_port: "{{mongodb_port}}"
    login_database: admin
    database: admin
    name: "{{mongodb_monitoring_username}}"
    password: "{{mongodb_monitoring_password}}"
    roles: clusterMonitor
    state: present